services:
  ollama:
    build:
      context: ./ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    ports:
      - "${HOST_PORT}:11434"
    volumes:
      - "${VOLUME_NAME}:/root/.ollama"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["/bin/sh", "-c", "./entrypoint.sh"]
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "${EMBEDDING_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  finetune:
    build:
      context: ./finetune
      # dockerfile: Dockerfile
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_TOKEN_MISTRAL_7B}
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    volumes:
      - ./data:/app/data  # mount your dataset here
      - ./output:/app/output  # save trained models
    working_dir: /app
    command: ["/bin/sh", "-c", "./finetune.sh"]
    stdin_open: true
    tty: true

volumes:
  qdrant_data:
  ollama_data:
