apiVersion: v1
kind: Service
metadata:
  name: agent-215-service
spec:
  selector:
    app: 215agent
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer